# Generated by Django 5.0.4 on 2024-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='inner_name',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
