# Generated by Django 5.0.4 on 2024-04-17 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_forumuser_banmessage_alter_forumuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(default=uuid.uuid4, max_length=64)),
                ('created_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='forumuser',
            old_name='banMessage',
            new_name='ban_message',
        ),
        migrations.RenameField(
            model_name='forumuser',
            old_name='bannedUntil',
            new_name='banned_until',
        ),
        migrations.RenameField(
            model_name='forumuser',
            old_name='isBanned',
            new_name='is_banned',
        ),
    ]
