# Generated by Django 5.0.4 on 2024-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_forumuser_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='created_invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='used_invites',
            field=models.IntegerField(default=0),
        ),
    ]
