# Generated by Django 5.0.4 on 2024-04-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_forumuser_created_invites_forumuser_used_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='invite_created_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.foruminvite'),
        ),
    ]
